// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo5e29NUlR6ClRf0i1mn6qPEiG_4LKM1A',
    appId: '1:635163660895:web:5396cc97460915e10801ea',
    messagingSenderId: '635163660895',
    projectId: 'chaina-bc74b',
    authDomain: 'chaina-bc74b.firebaseapp.com',
    storageBucket: 'chaina-bc74b.firebasestorage.app',
    measurementId: 'G-QRJV6YK20P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4VWIv7mUTuuMW4odYsw5FvzBhWsix3nQ',
    appId: '1:635163660895:android:839084ee5f107fd20801ea',
    messagingSenderId: '635163660895',
    projectId: 'chaina-bc74b',
    storageBucket: 'chaina-bc74b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPbdOzsFAkPM8feHGA9qvEbgLdnEruXWE',
    appId: '1:635163660895:ios:aa289b02d938d1970801ea',
    messagingSenderId: '635163660895',
    projectId: 'chaina-bc74b',
    storageBucket: 'chaina-bc74b.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPbdOzsFAkPM8feHGA9qvEbgLdnEruXWE',
    appId: '1:635163660895:ios:aa289b02d938d1970801ea',
    messagingSenderId: '635163660895',
    projectId: 'chaina-bc74b',
    storageBucket: 'chaina-bc74b.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo5e29NUlR6ClRf0i1mn6qPEiG_4LKM1A',
    appId: '1:635163660895:web:7d57a59bea9b2f430801ea',
    messagingSenderId: '635163660895',
    projectId: 'chaina-bc74b',
    authDomain: 'chaina-bc74b.firebaseapp.com',
    storageBucket: 'chaina-bc74b.firebasestorage.app',
    measurementId: 'G-LBQLSEDHJ6',
  );

}