// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD1myi7TfMuqqcKVsCfmlhCn9nSDrkH1M',
    appId: '1:729891947476:web:af2c081a525835303acc41',
    messagingSenderId: '729891947476',
    projectId: 'chineselearningapp-f0a96',
    authDomain: 'chineselearningapp-f0a96.firebaseapp.com',
    storageBucket: 'chineselearningapp-f0a96.firebasestorage.app',
    measurementId: 'G-MS5GLKD8NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC66TkN3QZ-fRu_GXo5tVKzYWv33A0Sp8k',
    appId: '1:729891947476:android:a52944ed094809f73acc41',
    messagingSenderId: '729891947476',
    projectId: 'chineselearningapp-f0a96',
    storageBucket: 'chineselearningapp-f0a96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAIvziOcZzTiLH3lKYq31uu7PAqN6M-pI',
    appId: '1:729891947476:ios:adc2ac5b78a126623acc41',
    messagingSenderId: '729891947476',
    projectId: 'chineselearningapp-f0a96',
    storageBucket: 'chineselearningapp-f0a96.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAIvziOcZzTiLH3lKYq31uu7PAqN6M-pI',
    appId: '1:729891947476:ios:adc2ac5b78a126623acc41',
    messagingSenderId: '729891947476',
    projectId: 'chineselearningapp-f0a96',
    storageBucket: 'chineselearningapp-f0a96.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD1myi7TfMuqqcKVsCfmlhCn9nSDrkH1M',
    appId: '1:729891947476:web:f476f70c5e9a65593acc41',
    messagingSenderId: '729891947476',
    projectId: 'chineselearningapp-f0a96',
    authDomain: 'chineselearningapp-f0a96.firebaseapp.com',
    storageBucket: 'chineselearningapp-f0a96.firebasestorage.app',
    measurementId: 'G-ZDHSEZVXZV',
  );

}